"""add user_id to tables

Revision ID: 03777465c92f
Revises: 
Create Date: 2026-06-11 19:53:45.257151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03777465c92f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema securely without losing existing row data."""
    # ### commands auto generated by Alembic - please adjust! ###

    # STEP 1: Add the columns safely as nullable=True so Postgres doesn't panic on old data
    op.add_column("daily_prices", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("gold_item", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("item_types", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("silver_item", sa.Column("user_id", sa.Integer(), nullable=True))

    # STEP 2: Handle the other auto-generated alterations (Foreign Keys & Type changes)
    op.create_foreign_key(
        None, "daily_prices", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "gold_item", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "item_types", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "silver_item", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )

    op.alter_column(
        "gold_item",
        "item_note",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "silver_item",
        "item_note",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )

    # STEP 3: Backfill your existing data rows with User ID 4 so they aren't empty
    op.execute("UPDATE daily_prices SET user_id = 4 WHERE user_id IS NULL")
    op.execute("UPDATE gold_item SET user_id = 4 WHERE user_id IS NULL")
    op.execute("UPDATE item_types SET user_id = 4 WHERE user_id IS NULL")
    op.execute("UPDATE silver_item SET user_id = 4 WHERE user_id IS NULL")

    # STEP 4: Lock down the columns to be strict NOT NULL now that data is populated
    op.alter_column("daily_prices", "user_id", nullable=False)
    op.alter_column("gold_item", "user_id", nullable=False)
    op.alter_column("item_types", "user_id", nullable=False)
    op.alter_column("silver_item", "user_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'silver_item', type_='foreignkey')
    op.alter_column('silver_item', 'item_note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('silver_item', 'user_id')
    op.drop_constraint(None, 'item_types', type_='foreignkey')
    op.drop_column('item_types', 'user_id')
    op.drop_constraint(None, 'gold_item', type_='foreignkey')
    op.alter_column('gold_item', 'item_note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('gold_item', 'user_id')
    op.drop_constraint(None, 'daily_prices', type_='foreignkey')
    op.drop_column('daily_prices', 'user_id')
    # ### end Alembic commands ###
