"""fix constraints for multi user setup

Revision ID: 6f1638781f64
Revises: 03777465c92f
Create Date: 2026-06-11 20:24:33.611481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1638781f64'
down_revision: Union[str, Sequence[str], None] = '03777465c92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_unique_constraint('uq_user_daily_price_data', 'daily_prices', ['user_id', 'date'])
    op.drop_index(op.f('ix_item_types_name'), table_name='item_types')
    op.create_index(op.f('ix_item_types_name'), 'item_types', ['name'], unique=False)
    op.create_unique_constraint('uq_user_item_type_name', 'item_types', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_item_type_name', 'item_types', type_='unique')
    op.drop_index(op.f('ix_item_types_name'), table_name='item_types')
    op.create_index(op.f('ix_item_types_name'), 'item_types', ['name'], unique=True)
    op.drop_constraint('uq_user_daily_price_data', 'daily_prices', type_='unique')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=True)
    # ### end Alembic commands ###
